// 由 Fugle API 產生之真實資料
const marketData = {
  twii_above_60ma: true,
  otc_above_60ma: true,
  vol_above_20ma: true,
  lastUpdate: '2026-05-14 14:10:23'
};

const mockStocks = [
  {
    "id": "3030",
    "name": "德律",
    "price": 414.0,
    "change": 6.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1411,
    "type": "D",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.8,
    "blacklist": []
  },
  {
    "id": "2360",
    "name": "致茂",
    "price": 2405.0,
    "change": -35.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 2566,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.4,
    "blacklist": []
  },
  {
    "id": "6788",
    "name": "華景電",
    "price": 454.0,
    "change": -11.0,
    "market": "OTC",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 998,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 13.2,
    "blacklist": []
  },
  {
    "id": "2330",
    "name": "台積電",
    "price": 2220.0,
    "change": -35.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 43727,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 3.9,
    "blacklist": []
  },
  {
    "id": "2317",
    "name": "鴻海",
    "price": 251.0,
    "change": 1.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 72415,
    "type": "D",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 1.0,
    "blacklist": []
  },
  {
    "id": "3231",
    "name": "緯創",
    "price": 140.5,
    "change": -1.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 26883,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 4.1,
    "blacklist": []
  },
  {
    "id": "3017",
    "name": "奇鋐",
    "price": 2585.0,
    "change": 65.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 6267,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 12.2,
    "blacklist": []
  },
  {
    "id": "2382",
    "name": "廣達",
    "price": 340.5,
    "change": 0.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 13159,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.7,
    "blacklist": []
  },
  {
    "id": "3481",
    "name": "群創",
    "price": 37.5,
    "change": 2.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 3.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1379646,
    "type": "A",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2303",
    "name": "聯電",
    "price": 98.4,
    "change": -6.1,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 352973,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 5.8,
    "blacklist": []
  },
  {
    "id": "2337",
    "name": "旺宏",
    "price": 168.0,
    "change": 15.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 239709,
    "type": "none",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 2.3,
    "blacklist": []
  },
  {
    "id": "0050",
    "name": "元大台灣50",
    "price": 95.5,
    "change": -1.35,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 130654,
    "type": "none",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.3,
    "blacklist": []
  },
  {
    "id": "0056",
    "name": "元大高股息",
    "price": 45.15,
    "change": -0.43,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 70167,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.3,
    "blacklist": []
  },
  {
    "id": "1303",
    "name": "南亞",
    "price": 86.5,
    "change": -2.6,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 56632,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.0,
    "blacklist": []
  },
  {
    "id": "0052",
    "name": "富邦科技",
    "price": 56.15,
    "change": -0.75,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 33153,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.4,
    "blacklist": []
  },
  {
    "id": "1101",
    "name": "台泥",
    "price": 24.7,
    "change": -0.25,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 24957,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 3.1,
    "blacklist": []
  },
  {
    "id": "1216",
    "name": "統一",
    "price": 75.2,
    "change": 2.1,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 24861,
    "type": "A",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "1314",
    "name": "中石化",
    "price": 7.02,
    "change": -0.06,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 20976,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 10.6,
    "blacklist": []
  },
  {
    "id": "1301",
    "name": "台塑",
    "price": 46.9,
    "change": -0.75,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 15755,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 13.9,
    "blacklist": []
  },
  {
    "id": "1326",
    "name": "台化",
    "price": 46.1,
    "change": -0.95,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 13784,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 15.6,
    "blacklist": []
  },
  {
    "id": "1102",
    "name": "亞泥",
    "price": 35.3,
    "change": 0.7,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 9747,
    "type": "none",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 2.1,
    "blacklist": []
  },
  {
    "id": "1312",
    "name": "國喬",
    "price": 10.9,
    "change": -0.6,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 9503,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 26.6,
    "blacklist": []
  },
  {
    "id": "1409",
    "name": "新纖",
    "price": 16.9,
    "change": 0.05,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 8017,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 3.7,
    "blacklist": []
  },
  {
    "id": "1402",
    "name": "遠東新",
    "price": 26.75,
    "change": 0.1,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 7092,
    "type": "D",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "1309",
    "name": "台達化",
    "price": 16.2,
    "change": -0.45,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 5867,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 28.2,
    "blacklist": []
  },
  {
    "id": "1304",
    "name": "台聚",
    "price": 13.0,
    "change": 0.25,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 5639,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 20.0,
    "blacklist": []
  },
  {
    "id": "1229",
    "name": "聯華",
    "price": 40.3,
    "change": -0.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 4180,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 9.2,
    "blacklist": []
  },
  {
    "id": "1310",
    "name": "台苯",
    "price": 8.35,
    "change": -0.17,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 4110,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 23.0,
    "blacklist": []
  },
  {
    "id": "1308",
    "name": "亞聚",
    "price": 13.35,
    "change": -0.1,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 3435,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 20.1,
    "blacklist": []
  },
  {
    "id": "1313",
    "name": "聯成",
    "price": 11.05,
    "change": -0.15,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 3105,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 16.3,
    "blacklist": []
  },
  {
    "id": "1305",
    "name": "華夏",
    "price": 13.0,
    "change": 0.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 2728,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 26.3,
    "blacklist": []
  },
  {
    "id": "1434",
    "name": "福懋",
    "price": 15.55,
    "change": -0.15,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 2387,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.8,
    "blacklist": []
  },
  {
    "id": "1440",
    "name": "南紡",
    "price": 11.85,
    "change": -0.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1958,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 13.8,
    "blacklist": []
  },
  {
    "id": "1210",
    "name": "大成",
    "price": 52.3,
    "change": 0.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1705,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 4.9,
    "blacklist": []
  },
  {
    "id": "1319",
    "name": "東陽",
    "price": 80.0,
    "change": 0.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1660,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.0,
    "blacklist": []
  },
  {
    "id": "1449",
    "name": "佳和",
    "price": 13.4,
    "change": -0.35,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1532,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 11.3,
    "blacklist": []
  },
  {
    "id": "1316",
    "name": "上曜",
    "price": 11.15,
    "change": -0.3,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1316,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.6,
    "blacklist": []
  },
  {
    "id": "1444",
    "name": "力麗",
    "price": 5.9,
    "change": -0.03,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1236,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 12.2,
    "blacklist": []
  }
];

// 評分邏輯 (滿分11分)
function calculateScore(stock) {
  let score = 0;
  if (stock.revYoY > 20) score += 1;
  if (stock.epsYoY > 15) score += 1;
  if (stock.roe > 10) score += 1;
  if (stock.dailyVol > 2000) score += 1;
  if (stock.marketCap > 50) score += 1;
  if (stock.trustDays >= 3) score += 1;
  if (stock.foreignBuy) score += 1;
  if (stock.maBull) score += 1;
  if (stock.volRatio > 1.5) score += 1;
  if (stock.closeToHigh) score += 1;
  if (stock.dist52W < 15) score += 1;
  return score;
}

mockStocks.forEach(s => s.score = calculateScore(s));
