// 由 Fugle API 產生之真實資料
const marketData = {
  twii_above_60ma: true,
  otc_above_60ma: true,
  vol_above_20ma: true,
  lastUpdate: '2026-05-13 08:42:27'
};

const mockStocks = [
  {
    "id": "3030",
    "name": "德律",
    "price": 408.0,
    "change": 11.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1406,
    "type": "D",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 2.3,
    "blacklist": []
  },
  {
    "id": "2360",
    "name": "致茂",
    "price": 2440.0,
    "change": 80.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 4455,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "6788",
    "name": "華景電",
    "price": 465.0,
    "change": -2.5,
    "market": "OTC",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 1326,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 11.1,
    "blacklist": []
  },
  {
    "id": "2330",
    "name": "台積電",
    "price": 2255.0,
    "change": 20.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 54239,
    "type": "none",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.4,
    "blacklist": []
  },
  {
    "id": "2317",
    "name": "鴻海",
    "price": 250.0,
    "change": -2.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 84325,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.4,
    "blacklist": []
  },
  {
    "id": "3231",
    "name": "緯創",
    "price": 141.5,
    "change": 2.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 75965,
    "type": "none",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 3.4,
    "blacklist": []
  },
  {
    "id": "3017",
    "name": "奇鋐",
    "price": 2520.0,
    "change": -35.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 5010,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 14.4,
    "blacklist": []
  },
  {
    "id": "2382",
    "name": "廣達",
    "price": 340.0,
    "change": -3.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 12855,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.9,
    "blacklist": []
  },
  {
    "id": "3481",
    "name": "群創",
    "price": 35.5,
    "change": 3.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 833426,
    "type": "A",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2409",
    "name": "友達",
    "price": 20.7,
    "change": 1.85,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 730161,
    "type": "A",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2303",
    "name": "聯電",
    "price": 104.5,
    "change": 9.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 383024,
    "type": "A",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2344",
    "name": "華邦電",
    "price": 121.5,
    "change": 4.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 317628,
    "type": "A",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2408",
    "name": "南亞科",
    "price": 321.0,
    "change": 20.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 217595,
    "type": "A",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "6770",
    "name": "力積電",
    "price": 62.1,
    "change": -0.4,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 170376,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.8,
    "blacklist": []
  },
  {
    "id": "2887",
    "name": "台新新光金",
    "price": 23.0,
    "change": -0.45,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 139438,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 7.8,
    "blacklist": []
  },
  {
    "id": "2337",
    "name": "旺宏",
    "price": 153.0,
    "change": -6.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 137568,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 11.0,
    "blacklist": []
  },
  {
    "id": "1802",
    "name": "台玻",
    "price": 71.1,
    "change": 1.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 132631,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 4.2,
    "blacklist": []
  },
  {
    "id": "0050",
    "name": "元大台灣50",
    "price": 96.85,
    "change": -0.05,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 102303,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.9,
    "blacklist": []
  },
  {
    "id": "2313",
    "name": "華通",
    "price": 260.0,
    "change": 18.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 93921,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 6.8,
    "blacklist": []
  },
  {
    "id": "2301",
    "name": "光寶科",
    "price": 234.5,
    "change": 10.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 91946,
    "type": "A",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2891",
    "name": "中信金",
    "price": 53.5,
    "change": -1.8,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 89185,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 5.1,
    "blacklist": []
  },
  {
    "id": "1717",
    "name": "長興",
    "price": 82.7,
    "change": 1.9,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 77114,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2883",
    "name": "凱基金",
    "price": 21.6,
    "change": -1.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.5,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 75956,
    "type": "none",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 5.7,
    "blacklist": []
  },
  {
    "id": "0056",
    "name": "元大高股息",
    "price": 45.58,
    "change": -0.18,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 71013,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.4,
    "blacklist": []
  },
  {
    "id": "2377",
    "name": "微星",
    "price": 105.0,
    "change": -2.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 3.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 67323,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.3,
    "blacklist": []
  },
  {
    "id": "1303",
    "name": "南亞",
    "price": 89.1,
    "change": -2.4,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 63621,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 5.2,
    "blacklist": []
  },
  {
    "id": "2327",
    "name": "國巨*",
    "price": 419.5,
    "change": 28.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 63365,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2481",
    "name": "強茂",
    "price": 115.5,
    "change": 6.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 61667,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.1,
    "blacklist": []
  },
  {
    "id": "2367",
    "name": "燿華",
    "price": 64.8,
    "change": 2.2,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 57458,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 12.4,
    "blacklist": []
  },
  {
    "id": "2890",
    "name": "永豐金",
    "price": 30.55,
    "change": -0.05,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 54546,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.3,
    "blacklist": []
  },
  {
    "id": "2312",
    "name": "金寶",
    "price": 29.45,
    "change": -0.45,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 53924,
    "type": "D",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 2.2,
    "blacklist": []
  },
  {
    "id": "3714",
    "name": "富采",
    "price": 73.7,
    "change": 5.8,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 52502,
    "type": "none",
    "maBull": true,
    "closeToHigh": true,
    "dist52W": 6.0,
    "blacklist": []
  },
  {
    "id": "2324",
    "name": "仁寶",
    "price": 29.9,
    "change": -0.9,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 51063,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.7,
    "blacklist": []
  },
  {
    "id": "4919",
    "name": "新唐",
    "price": 181.0,
    "change": -3.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 48844,
    "type": "B",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 1.6,
    "blacklist": []
  },
  {
    "id": "2884",
    "name": "玉山金",
    "price": 31.8,
    "change": -0.5,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 48368,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 3.8,
    "blacklist": []
  },
  {
    "id": "2002",
    "name": "中鋼",
    "price": 18.5,
    "change": -0.1,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 46640,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 9.8,
    "blacklist": []
  },
  {
    "id": "2882",
    "name": "國泰金",
    "price": 76.4,
    "change": -2.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 44745,
    "type": "none",
    "maBull": true,
    "closeToHigh": false,
    "dist52W": 4.5,
    "blacklist": []
  },
  {
    "id": "3036",
    "name": "文曄",
    "price": 275.5,
    "change": 11.0,
    "market": "TSE",
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 3.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 43177,
    "type": "A",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  }
];

// 評分邏輯 (滿分11分)
function calculateScore(stock) {
  let score = 0;
  if (stock.revYoY > 20) score += 1;
  if (stock.epsYoY > 15) score += 1;
  if (stock.roe > 10) score += 1;
  if (stock.dailyVol > 2000) score += 1;
  if (stock.marketCap > 50) score += 1;
  if (stock.trustDays >= 3) score += 1;
  if (stock.foreignBuy) score += 1;
  if (stock.maBull) score += 1;
  if (stock.volRatio > 1.5) score += 1;
  if (stock.closeToHigh) score += 1;
  if (stock.dist52W < 15) score += 1;
  return score;
}

mockStocks.forEach(s => s.score = calculateScore(s));
