// 由 Fugle API 產生之真實資料
const marketData = {
  twii_above_60ma: true,
  otc_above_60ma: true,
  vol_above_20ma: true,
  lastUpdate: '2026-05-12 13:13:39'
};

const mockStocks = [
  {
    "id": "3481",
    "name": "群創",
    "price": 32.3,
    "change": 2.9,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 417999,
    "type": "none",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2409",
    "name": "友達",
    "price": 18.85,
    "change": 1.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 317856,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 8.9,
    "blacklist": []
  },
  {
    "id": "6770",
    "name": "力積電",
    "price": 62.5,
    "change": 1.1,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 283121,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 2.2,
    "blacklist": []
  },
  {
    "id": "2303",
    "name": "聯電",
    "price": 95.0,
    "change": 3.7,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 178723,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 1.6,
    "blacklist": []
  },
  {
    "id": "2344",
    "name": "華邦電",
    "price": 117.5,
    "change": 10.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 162759,
    "type": "D",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2337",
    "name": "旺宏",
    "price": 159.5,
    "change": 6.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 149221,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 7.3,
    "blacklist": []
  },
  {
    "id": "3231",
    "name": "緯創",
    "price": 139.0,
    "change": 7.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 114217,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 5.1,
    "blacklist": []
  },
  {
    "id": "2408",
    "name": "南亞科",
    "price": 301.0,
    "change": 27.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 108987,
    "type": "D",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2887",
    "name": "台新新光金",
    "price": 23.45,
    "change": 0.35,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 98201,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 6.0,
    "blacklist": []
  },
  {
    "id": "0050",
    "name": "元大台灣50",
    "price": 96.9,
    "change": 0.1,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 96606,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.8,
    "blacklist": []
  },
  {
    "id": "6282",
    "name": "康舒",
    "price": 55.4,
    "change": 5.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 90352,
    "type": "A",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "6116",
    "name": "彩晶",
    "price": 9.71,
    "change": 0.51,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 3.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 89842,
    "type": "A",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2312",
    "name": "金寶",
    "price": 29.9,
    "change": 1.95,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 88274,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.7,
    "blacklist": []
  },
  {
    "id": "1717",
    "name": "長興",
    "price": 80.8,
    "change": 2.9,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 84480,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 2.3,
    "blacklist": []
  },
  {
    "id": "2313",
    "name": "華通",
    "price": 242.0,
    "change": 11.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 81477,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 13.3,
    "blacklist": []
  },
  {
    "id": "2324",
    "name": "仁寶",
    "price": 30.8,
    "change": 1.15,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 81430,
    "type": "none",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 6.0,
    "blacklist": []
  },
  {
    "id": "1802",
    "name": "台玻",
    "price": 69.9,
    "change": 1.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.4,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 78048,
    "type": "D",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 5.8,
    "blacklist": []
  },
  {
    "id": "1605",
    "name": "華新",
    "price": 35.0,
    "change": 1.25,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.9,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 74486,
    "type": "none",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 2.4,
    "blacklist": []
  },
  {
    "id": "0056",
    "name": "元大高股息",
    "price": 45.76,
    "change": 0.91,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 70902,
    "type": "D",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2610",
    "name": "華航",
    "price": 19.15,
    "change": 0.6,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.3,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 64895,
    "type": "A",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2449",
    "name": "京元電子",
    "price": 299.5,
    "change": 11.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 63413,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 15.4,
    "blacklist": []
  },
  {
    "id": "2317",
    "name": "鴻海",
    "price": 252.0,
    "change": 2.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.7,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 63063,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.6,
    "blacklist": []
  },
  {
    "id": "1303",
    "name": "南亞",
    "price": 91.5,
    "change": 2.9,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 0.6,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 53717,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 2.7,
    "blacklist": []
  },
  {
    "id": "2327",
    "name": "國巨*",
    "price": 391.5,
    "change": 2.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 51692,
    "type": "D",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "8150",
    "name": "南茂",
    "price": 91.0,
    "change": 1.7,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 51675,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 7.2,
    "blacklist": []
  },
  {
    "id": "2891",
    "name": "中信金",
    "price": 55.3,
    "change": 1.1,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.0,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 50449,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 2.0,
    "blacklist": []
  },
  {
    "id": "4919",
    "name": "新唐",
    "price": 184.0,
    "change": 16.5,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 2.2,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 50067,
    "type": "A",
    "maBull": false,
    "closeToHigh": true,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2002",
    "name": "中鋼",
    "price": 18.6,
    "change": 0.15,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 49013,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 9.3,
    "blacklist": []
  },
  {
    "id": "2353",
    "name": "宏碁",
    "price": 28.8,
    "change": 1.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.8,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 46873,
    "type": "A",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 0.0,
    "blacklist": []
  },
  {
    "id": "2330",
    "name": "台積電",
    "price": 2235.0,
    "change": 55.0,
    "epsYoY": 20,
    "revYoY": 25,
    "roe": 12,
    "grossMargin": 30,
    "debtRatio": 45,
    "trustDays": 3,
    "foreignBuy": true,
    "volRatio": 1.1,
    "turnover": 5.0,
    "marketCap": 200,
    "dailyVol": 46172,
    "type": "none",
    "maBull": false,
    "closeToHigh": false,
    "dist52W": 3.2,
    "blacklist": []
  }
];

// 評分邏輯 (滿分11分)
function calculateScore(stock) {
  let score = 0;
  if (stock.revYoY > 20) score += 1;
  if (stock.epsYoY > 15) score += 1;
  if (stock.roe > 10) score += 1;
  if (stock.dailyVol > 2000) score += 1;
  if (stock.marketCap > 50) score += 1;
  if (stock.trustDays >= 3) score += 1;
  if (stock.foreignBuy) score += 1;
  if (stock.maBull) score += 1;
  if (stock.volRatio > 1.5) score += 1;
  if (stock.closeToHigh) score += 1;
  if (stock.dist52W < 15) score += 1;
  return score;
}

mockStocks.forEach(s => s.score = calculateScore(s));
